export enum AuthConstants {
  SIGN_IN = 'AUTH/SIGH_IN',
  LOGOUT = 'AUTH/LOGOUT',
}

export enum UserConstants {}

export enum AppConstants {
  LOADING_ON = 'APP/LOADING_ON',
  LOADING_OFF = 'APP/LOADING_OFF',

  ALERT_CALL = 'APP/ALERT_CALL',
  ALERT_FILL_CONTENT = 'APP/ALERT_FILL_CONTENT',
  ALERT_CLEAR_CONTENT = 'APP/ALERT_CLEAR_CONTENT',
}
